### ISSUE TITLE
Moving nodes

### ISSUE THREAD

**Issue by mumbomediaAlexander** [splitt3r/mindmaps#55] opened 2018-05-27 12:46 UTC
When developing a mindmap it is not unusal that your have to reorder nodes. 

Actual I have to delete the child nodes an recreate them. This involves the danger of forgetting some nodes.
Therefore, it would be great if you could move (drag n' drop) the nodes freely.

Also, I think that in times of excessive smartphone / tablet use the touchscreen support is absolutely necessary.

**Comment by splitt3r** [comment] 2018-05-27 13:12
Duplicate of #42

**Closed by splitt3r** 2018-05-27 13:12 UTC
