### ISSUE TITLE
Question: 32-bit PHP support

### ISSUE THREAD

**Issue by sunjam** [splitt3r/mindmaps#39] opened 2018-02-20 05:10 UTC
Unable to install Mindmaps on a Raspberry Pi 32-bit ARM device, because 64-bit PHP is required.  Is 32-bit support available?

**Comment by splitt3r** [comment] 2018-02-20 05:32
The next release will fix this. Duplicate of #36

**Closed** 2018-02-20 08:04 UTC
Labels: question

**Comment by splitt3r** [comment] 2018-03-10 21:29
@sunjam @aseedorf new version is out now :)
